<div class="design-professional">
    <div class="dp-title">
        <?= $block->escapeHtml(__('Let’s make something')) ?>
    </div>
    <p class="dp-subtitle"><?= $block->escapeHtml(__('Need more options? Some ideas are too big for self-serve.')) ?></p>
    <div class="dp-row">
        <div class="dp-box">
            <a href="/myaccount/EstimateRequest.html" class="dp-padding">
                <span class="dp-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="90.072" height="92.741" viewBox="0 0 90.072 92.741">
                        <g data-name="Group 1305" transform="translate(-54.585 -54)">
                            <g  transform="translate(54.585 54)">
                            <rect data-name="Rectangle 481" width="85.04" height="85.04" transform="translate(0.054)" fill="none"/>
                            <path data-name="Path 146" d="M42.547,0A42.547,42.547,0,1,0,85.094,42.547,42.672,42.672,0,0,0,42.547,0Zm-.425,70.628a5.957,5.957,0,1,1,5.957-5.957A5.816,5.816,0,0,1,42.122,70.628ZM53.609,37.441l-4.68,5.106a5.2,5.2,0,0,0-1.7,3.829,5.174,5.174,0,0,1-5.106,5.106,4.916,4.916,0,0,1-5.106-5.106c0-2.553.425-4.68,3.4-7.658l3.829-4.68c2.127-2.553,2.978-4.255,2.978-5.957a4.464,4.464,0,0,0-4.68-4.68,5.005,5.005,0,0,0-5.106,3.829,5.556,5.556,0,0,1-5.106,2.978,4.464,4.464,0,0,1-4.68-4.68,4.626,4.626,0,0,1,.425-2.127c1.7-5.106,6.808-8.935,14.466-8.935,8.935,0,14.891,5.957,14.891,13.615A13.959,13.959,0,0,1,53.609,37.441Z" fill="#0c2340"/>
                            </g>
                            <path data-name="Polygon 135" d="M9.837,0l9.837,19.674H0Z" transform="translate(144.657 132.829) rotate(135)" fill="#0c2340"/>
                        </g>
                    </svg>
                </span>
                <span class="dp-title__sub"><?= $block->escapeHtml(__('Get an estimate')) ?></span>
                <span class="dp-discription"><?= $block->escapeHtml(__('Get started with an estimate to create your project.')) ?></span>
            </a>
        </div>
        <div class="dp-box">
            <a href="/locations/" class="dp-padding">
                <span class="dp-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="102" height="115" viewBox="0 0 102 115">
                        <g data-name="Group 1252" transform="translate(0.408 0.305)">
                            <g data-name="icon/maps/place_24px" transform="translate(-0.408 -0.267)">
                            <rect width="102" height="102" transform="translate(0 -0.038)" fill="none"/>
                            <path data-name=" ↳Color" d="M29.5,87l0,0A196.945,196.945,0,0,1,14.75,67.289C8.021,56.995,0,42.248,0,30.451A30.758,30.758,0,0,1,8.634,8.913a28.881,28.881,0,0,1,41.732,0A30.758,30.758,0,0,1,59,30.451c0,11.8-8.021,26.544-14.75,36.838A196.946,196.946,0,0,1,29.5,87Zm0-67.425A10.722,10.722,0,0,0,18.964,30.451,10.722,10.722,0,0,0,29.5,41.327,10.722,10.722,0,0,0,40.036,30.451,10.722,10.722,0,0,0,29.5,19.575Z" transform="translate(21 7.962)" fill="#0c2340"/>
                            </g>
                            <ellipse data-name="Ellipse 29" cx="22" cy="5.5" rx="22" ry="5.5" transform="translate(28.592 103.695)" fill="#0c2340"/>
                        </g>
                    </svg>
                </span>
                <span class="dp-title__sub"><?= $block->escapeHtml(__('Find a location')) ?></span>
                <span class="dp-discription"><?= $block->escapeHtml(__('Get in touch with a production centre near you.')) ?></span>
            </a>
        </div>
    </div>
</div>